name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - staging
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Build on EAS
        run: echo "::set-output name=ARTIFACT_URL::$(eas build --platform ios --profile preview --non-interactive | grep 'https://expo.dev/artifacts/')"
        id: eas-build
      - name: Download Artifact
        run: cd ci; python download.py ${{ steps.eas-build.outputs.ARTIFACT_URL }}
      - name: Commit Artifact
        run: |
          git add .
          git config --global user.name 'Michael Ryan'
          git config --global user.email 'xenonmolecule@users.noreply.github.com'
          git commit -am "Automatic Artifact Build"
          git push
